title: "My GitHub Page"
description: "A personal site built using GitHub Pages and Jekyll."
theme: minima   # Default GitHub Pages theme
author: Brian Zebosi
email: zebosibrian@gmail.com
url: "https://bzebosi.github.io"  # Replace <username> with your GitHub username
baseurl: ""   # Leave empty unless the site is in a subdirectory