layout: stacked
style: light

plugins:
  - jekyll-octicons
  - jekyll-github-metadata
  - jemoji

permalink: /:year/:month/:day/:title/

defaults:
  -
    scope:
      path: "" 
      type: "posts"
    values:
      layout: "post"

projects:
  sort_by options:
    - pushed
    - stars
  limit: 9
  exclude:
    archived: false
    forks: true
    projects:

social_media:
  email: zebosibrian@gmail.com
  orcid: 0000-0001-6802-3274
  linkedin: zebosi-brian-a76b07100
  github: bzebosi
  twitter: zebrimas